# Generated by Django 4.2.8 on 2024-01-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='emoji',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
