# Generated by Django 4.2.8 on 2024-01-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_recipe_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='emoji',
        ),
        migrations.AddField(
            model_name='recipe',
            name='icon',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
